name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Construção imagem docker
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            antoniogabriel/kube-news:v1
            antoniogabriel/kube-news:latest
            
